### ISSUE TITLE
Vundle support

### ISSUE THREAD

**Issue by alexluecke** [mswift42/vim-themes#1]
Not sure if it is something poorly configured in my vimrc, but colorschemes aren't recognized when repo is installed through Vundle. E.g. running `colorscheme darktooth` shows `cannot find color scheme` error. I will look into this more when I am not tired.

**Comment by flipcoder** [comment]
Fixed: https://github.com/mswift42/vim-themes/pull/2

**Comment by mswift42** [comment]
Fixed: https://github.com/mswift42/vim-themes/commit/1c1c780ffa920a6579a6fb87bf6a9488d8be4a02
